services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
      INFO: 1
      VERSION: 1
      EXEC: 1
      SYSTEM: 1
      POST: 1
      GET: 1
      TZ: "Africa/Nairobi"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      portainer_default:
        ipv4_address: 172.30.0.30
    ports:
      - "127.0.0.1:2375:2375"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
          pids: 50
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

networks:
  portainer_default:
    external: true
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
