services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8180:80/tcp"
      - "8443:443/tcp"
    environment:
      - TZ=Africa/Nairobi
      - ADGUARD_LOG_LEVEL=trace
      - ADGUARD_VERBOSE=true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    networks:
      portainer_default:
        ipv4_address: 172.30.0.53
    volumes:
      - /opt/adguardhome/work:/opt/adguardhome/work
      - /opt/adguardhome/conf:/opt/adguardhome/conf
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
networks:
  portainer_default:
    external: true
