services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8180:80/tcp"
      - "3000:3000/tcp"
    environment:
      - TZ=Africa/Nairobi
      - ADGUARD_VERBOSE=true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      internal_network:
        ipv4_address: 172.30.0.53
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
    volumes:
      - /opt/docker/adguardhome/work:/opt/adguardhome/work
      - /opt/docker/adguardhome/conf:/opt/adguardhome/conf
        
networks:
  internal_network:
    external: true
