services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8180:80/tcp"
      - "3000:3000/tcp"
    environment:
      - TZ=Africa/Nairobi
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      internal_network:
        ipv4_address: 172.30.0.53
    dns:
      - 172.30.0.54
    volumes:
      - /opt/docker/adguardhome/work:/opt/adguardhome/work
      - /opt/docker/adguardhome/conf:/opt/adguardhome/conf
    tmpfs:
      - /tmp
      - /run

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: always
    networks:
      internal_network:
        ipv4_address: 172.30.0.54
    volumes:
      - /opt/docker/unbound/root.hints:/var/lib/unbound/root.hints
      
networks:
  internal_network:
    external: true
