services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    user: "1000:1000"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8180:80/tcp"
      - "3000:3000/tcp"
    environment:
      - TZ=Africa/Nairobi
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      internal_network:
        ipv4_address: 172.30.0.53
    dns:
      - 127.0.0.1
    volumes:
      - /opt/docker/adguardhome/work:/opt/adguardhome/work
      - /opt/docker/adguardhome/conf:/opt/adguardhome/conf
        
networks:
  internal_network:
    external: true
