services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8180:80/tcp"
    environment:
      - TZ=Africa/Nairobi
      - ADGUARD_VERBOSE=true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      internal_network:
        ipv4_address: 172.30.0.53
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
    volumes:
      - /opt/adguardhome/work:/opt/adguardhome/work
      - /opt/adguardhome/conf:/opt/adguardhome/conf
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
        
networks:
  portainer_default:
    external: true
