services:
  tor:
    image: dockurr/tor
    container_name: tor
    restart: always
    user: "1000:1000"
    ports:
      - 9050:9050
    networks:
      - external_network
    volumes:
      - /docker/tor/config:/etc/tor
      - /docker/tor/data:/var/lib/tor
networks:
  external_network:
    external: true
