services:

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
      INFO: 1
      VERSION: 1
      EXEC: 1
      SYSTEM: 1
      POST: 1
      GET: 1
      TZ: "Africa/Nairobi"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      portainer_default:
        ipv4_address: 172.30.0.30
    ports:
      - "127.0.0.1:2375:2375"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - TZ=Africa/Nairobi
    ports:
      - "8880:8080"
    networks:
      - portainer_default
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - TZ=Africa/Nairobi
    ports:
      - "3001:3000"
    networks:
      - portainer_default
    volumes:
      - /opt/homepage/config:/app/config

  code-server:
    image: lscr.io/linuxserver/code-server:4.96.4-ls254
    container_name: code-server
    restart: unless-stopped
    privileged: true
    environment:
      - PUID=1000 
      - PGID=1000
      - TZ=Africa/Nairobi
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - DEFAULT_WORKSPACE=/config/workspace
      - PROXY_DOMAIN=code.lenadlm.dev # Uncomment if using a reverse proxy
    ports:
      - "8443:8443"
    networks:
      - portainer_default
    volumes:
      - /opt/code-server/config:/config
      - /opt:/config/workspace/array
 
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    restart: unless-stopped
    environment:
      - PUID=1000 
      - PGID=1000
      - TZ=Africa/Nairobi
    ports:
      - 82:80
    networks:
      - portainer_default
    volumes:
      - /opt/ntfy/var/cache:/var/cache
      - /opt/ntfy/etc/ntfy:/etc/ntfy

  samsung-tvplus:
    image: matthuisman/samsung-tvplus-for-channels
    container_name: samsung-tvplus
    restart: unless-stopped
    environment:
      - REGIONS=all
      - TZ=Africa/Nairobi
    ports:
      - "8182:80"
    networks:
      - portainer_default

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - TZ=Africa/Nairobi
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_NOTIFICATIONS=gotify 
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=${WATCHTOWER_NOTIFICATION_GOTIFY_URL}
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN}
    networks:
      - portainer_default
    volumes:
      - /home/lenadlm/.docker/config.json:/config.json

networks:
  portainer_default:
    external: true
