services:

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - POST=1
      - SERVICES=1
      - SYSTEM=1
      - VERSION=1
      - TZ=Africa/Nairobi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      internal_network:
        ipv4_address: 172.30.0.30
    ports:
      - "127.0.0.1:2375:2375" 
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - TZ=Africa/Nairobi
    security_opt:
      - no-new-privileges:true
    ports:
      - "8880:8080"
    networks:
      - internal_network
    cap_drop:
      - ALL
    volumes:
      - /opt/docker/dozzle/data:/data
    depends_on:
      - docker-socket-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - TZ=Africa/Nairobi
    ports:
      - "3001:3000"
    networks:
      - internal_network
    volumes:
      - /opt/docker/homepage/config:/app/config

  code-server:
    image: lscr.io/linuxserver/code-server:4.96.4-ls254
    container_name: code-server
    restart: unless-stopped
    environment:
      - PUID=1000 
      - PGID=1000
      - TZ=Africa/Nairobi
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - DEFAULT_WORKSPACE=/config/workspace
    ports:
      - "8443:8443"
    networks:
      - internal_network
    volumes:
      - /opt/docker/code-server/config:/config
      - /opt:/config/workspace/array
 
# gotify:
#   image: ghcr.io/gotify/server:latest
#   container_name: gotify
#   restart: unless-stopped
#   ports:
#     - "8480:80"
#   environment:
#     - TZ=Africa/Nairobi
#   networks:
#     - internal_network
#   volumes:
#     - /opt/docker/gotify/data:/app/data

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PUID=1000 
      - PGID=1000
      - TZ=Africa/Nairobi
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - internal_network
    volumes:
      - /opt/docker/syncthing/config:/config
      - /opt:/opt
      - /opt/docker:/opt/docker
    
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - TZ=Africa/Nairobi
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_NOTIFICATIONS=telegram
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=UBUNTU-GCP01
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
    networks:
      - internal_network
    volumes:
      - /opt/docker/watchtower/config.json:/config.json
    depends_on:
      - docker-socket-proxy

networks:
  internal_network:
    external: true
