services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORTAINER_THEME=dark
    networks:
      internal_network:
        ipv4_address: 172.30.0.10
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"

volumes:
  data:

networks:
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
    attachable: true

  external_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
    attachable: true
