services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    volumes:
      - ./fail2ban-data:/data
      - /etc/fail2ban/jail.local:/data/jail.local
      - /var/log/fail2ban.log:/data/fail2ban.log
      - /var/log/auth.log:/data/auth.log
      - /var/run/fail2ban:/var/run/fail2ban
    command: /bin/sh -c "mkdir -p /var/run/fail2ban && exec fail2ban-server -f"
    environment:
      - F2B_LOGTARGET=STDOUT
      - TZ=Africa/Nairobi
    restart: unless-stopped

  fail2rest:
    image: dietermartens/fail2rest:latest
    container_name: fail2rest
    ports:
      - "5000:5000"
    environment:
      - F2B_FAIL2BAN_SOCKET=/var/run/fail2ban/fail2ban.sock
    depends_on:
      - fail2ban
    restart: unless-stopped

  fail2web:
    image: dietermartens/fail2web:latest
    container_name: fail2web
    ports:
      - "8180:80"
    environment:
      - FAIL2WEB_F2BAN_SOCKET=/var/run/fail2ban/fail2ban.sock
    depends_on:
      - fail2ban
    restart: unless-stopped

volumes:
  fail2ban-data:
