
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - VERSION=docker
      # - PLEX_CLAIM= # Optional, replace with claim token if needed
    volumes:
      - /d/data/docker/plex/config:/config   # Plex library configuration
      - /d/data/docker/plex/data:/data 
      - /d/data/docker/media:/media
    networks:
      - portainer_default
    dns:
      - 172.30.0.53
networks:
  portainer_default:
    external: true
