version: '3.8'
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - /opt/docker/crowdsec/data:/var/lib/crowdsec/data
      - /opt/docker/crowdsec/config:/etc/crowdsec
    networks:
      - external_network

  cloudflare-bouncer:
    image: crowdsecurity/cloudflare-bouncer:latest
    container_name: cloudflare-bouncer
    environment:
      - CROWDSEC_LAPI_URL=http://crowdsec:8080
      - CROWDSEC_LAPI_KEY=${CROWDSEC_LAPI_KEY}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
    restart: unless-stopped
    depends_on:
      - crowdsec
    networks:
      - external_network

networks:
  external_network:
    external: true
