  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - 80:80
    networks:
      internal_network:
        ipv4_address: 172.30.0.53
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - SYS_TIME
    environment:
      - TZ=Africa/Nairobi
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - ${DATADIR}/pihole/pihole:/etc/pihole
      - ${DATADIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
networks:
  internal_network:
    external: true
