services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    environment:
      TZ: "Africa/Nairobi"
      WEBPASSWORD: "pihole"
    volumes:
      - /d/data/docker/pihole/etc-pihole:/etc/pihole
      - /d/data/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
    networks:
      - portainer_default
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

networks:
  portainer_default:
    external: true
