services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=miqrata9j@mozmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Port for the Traefik dashboard (secured with Basic Auth)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt  # Store Let's Encrypt certificates
    networks:
      - traefik
    labels:
      - "traefik.http.routers.traefik.rule=Host(`xxx.mydomain.com`)"  # Replace with your domain
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=auth@docker"  # Apply the Basic Auth middleware
      - "traefik.http.middlewares.auth.basicauth.users=user:password"
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`xxx.mydomain.com`)" # Change to your domain
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    volumes:
      - /opt/docker/adguardhome/conf:/opt/adguardhome/conf
      - /opt/docker/adguardhome/work:/opt/adguardhome/work
    networks:
      - traefik
    ports:
      - "53:53/tcp"   # DNS over TCP
      - "53:53/udp"   # DNS over UDP
      - "853:853/tcp" # DNS over TLS
      - "784:784/tcp" # DNS over HTTPS
      - "3000:80/tcp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`xxx.mydomain.com`)" # Change to your domain
      - "traefik.http.services.adguard.loadbalancer.server.port=3000" # Default AdGuard Home port

networks:
  traefik:
    driver: bridge

volumes:
  portainer_data:
