services:
  dnsdist:
    image: powerdns/dnsdist-20:latest
    container_name: dnsdist
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      internal_network:
        ipv4_address: 172.30.0.53
      external_network:
        ipv4_address: 172.20.0.53
    cap_add:
      - NET_BIND_SERVICE
      - NET_ADMIN
    volumes:
      - /opt/docker/dnsdist:/etc/dnsdist

  unbound1:
    image: alpinelinux/unbound:latest
    container_name: unbound1
    restart: always
    networks:
      internal_network:
        ipv4_address: 172.30.0.54
    volumes:
      - /opt/docker/unbound/1/unbound.conf:/etc/unbound/unbound.conf
      - /opt/docker/unbound/1/root.hints:/etc/unbound/root.hints
      - /etc/timezone:/etc/timezone:ro
    tmpfs:
      - /tmp
      - /var/lib/unbound

networks:
  internal_network:
    external: true
  external_network:
    external: true
