services:
  tor:
    container_name: tor
    image: lenadlm000/tor:latest
    restart: always
    ports:
      - "9050:9050"
      - "9051:9051"
    volumes:
      - /d/data/docker/tor:/etc/tor
    networks:
      - external_network
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  
networks:
  external_network:
    external: true
