# Use Alpine as the base image
FROM alpine:latest

# Install Tor
RUN apk update && apk add --no-cache tor

# Copy torrc from the build directory into the container
COPY torrc /etc/tor/torrc

# Ensure the torrc file is owned by the Tor user
RUN chown -R tor /etc/tor

# Switch to the Tor user
USER tor

# Set the entrypoint and default command
ENTRYPOINT ["tor"]
CMD ["-f", "/etc/tor/torrc"]
