services:

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - external_network

  #cloudflare-ddns:
  #  image: favonia/cloudflare-ddns:latest
  #  restart: unless-stopped
  #  user: "1000:1000"
  #  read_only: true
  #  cap_drop: [all]
  #  security_opt: [no-new-privileges:true]
  #  environment:
  #    - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
  #    - DOMAINS=${DOMAINS}
  #    - PROXIED=true
  #  networks:
  #    - external_network

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    networks:
      - external_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - ${DATADIR}/duckdns/config:/config
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - 80:80
    networks:
      external_network:
        ipv4_address: 172.20.0.53
    dns:
      - 127.0.0.1
      - 127.30.0.54
      - 127.20.0.54
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    environment:
      - TZ=Africa/Nairobi
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - ${DATADIR}/pihole/pihole:/etc/pihole
      - ${DATADIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /etc/timezone:/etc/timezone:ro

  unbound1:
    image: alpinelinux/unbound:latest
    container_name: unbound1
    restart: always
    networks:
      internal_network:
        ipv4_address: 172.30.0.54
    volumes:
      - ${DATADIR}/unbound:/etc/unbound
      - /etc/timezone:/etc/timezone:ro
    tmpfs:
      - /tmp
      - /var/lib/unbound

  unbound2:
    image: alpinelinux/unbound:latest
    container_name: unbound2
    restart: always
    networks:
      external_network:
        ipv4_address: 172.20.0.54
    volumes:
      - ${DATADIR}/unbound:/etc/unbound
      - /etc/timezone:/etc/timezone:ro
    tmpfs:
      - /tmp
      - /var/lib/unbound

networks:
  external_network:
    external: true
