services:

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - external_network

  #cloudflare-ddns:
  #  image: favonia/cloudflare-ddns:latest
  #  restart: unless-stopped
  #  user: "1000:1000"
  #  read_only: true
  #  cap_drop: [all]
  #  security_opt: [no-new-privileges:true]
  #  environment:
  #    - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
  #    - DOMAINS=${DOMAINS}
  #    - PROXIED=true
  #  networks:
  #    - external_network

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    networks:
      - external_network
    environment:
      - PUID=1000  # Optional
      - PGID=1000  # Optional
      - TZ=Africa/Nairobi  # Optional
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
      - UPDATE_IP=ipv4  # Optional
      - LOG_FILE=false  # Optional
    volumes:
      - ${DATADIR}/duckdns/config:/config  # Adjust path as needed
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - 80:80
    networks:
      external_network:
        ipv4_address: 172.20.0.53
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - SYS_TIME
    environment:
      - TZ=Africa/Nairobi
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - ${DATADIR}/pihole/pihole:/etc/pihole
      - ${DATADIR}/pihole/dnsmasq.d:/etc/dnsmasq.d

networks:
  external_network:
    external: true
