services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - CONTAINERS=1
      - GET=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - POST=1
      - SERVICES=1
      - SYSTEM=1
      - VERSION=1
      - TZ=Africa/Nairobi
    networks:
      - internal_network
      - external_network
    ports:
      - "127.0.0.1:2375:2375" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - external_network

  #duckdns:
  #  image: lscr.io/linuxserver/duckdns:latest
  #  container_name: duckdns
  #  restart: unless-stopped
  #  networks:
  #    - external_network
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Africa/Nairobi
  #    - SUBDOMAINS=${SUBDOMAINS}
  #    - TOKEN=${TOKEN}
  #    - UPDATE_IP=ipv4
  #    - LOG_FILE=false
  #  volumes:
  #    - /docker/duckdns/config:/config
      
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Africa/Nairobi
      - PUID=1001
      - PGID=1001
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - external_network
    cap_add:
      - CHOWN
      - FOWNER
    volumes:
      - /docker/syncthing/config:/config:rw
      - /docker:/docker:rw

  samsung-tvplus:
    image: matthuisman/samsung-tvplus-for-channels
    container_name: samsung-tvplus
    restart: unless-stopped
    environment:
      - TZ=Africa/Nairobi
    ports:
      - "8182:80"
    networks:
      - external_network

  xteve:
    image: tinyserve/xteve:latest
    container_name: xteve
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Africa/Nairobi
    networks:
      - external_network
    ports:
      - "34400:34400"
    volumes:
      - /docker/xteve:/etc/xteve
 
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - TZ=Africa/Nairobi
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=UBUNTU-PVE
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
    networks:
      - internal_network
      - external_network
    volumes:
      - /docker/watchtower/config.json:/config.json
    depends_on:
      - docker-socket-proxy

networks:
  internal_network:
    external: true
  external_network:
    external: true
