services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 172.30.0.10
    restart: unless-stopped

volumes:
  portainer_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8180:80/tcp"
      - "8443:443/tcp"
      - "3000:3000/tcp"
    volumes:
      - /opt/adguardhome/work:/opt/adguardhome/work
      - /opt/adguardhome/conf:/opt/adguardhome/conf
     environment:
      - TZ=Africa/Nairobi
    networks:
      portainer_default:
        ipv4_address: 172.30.0.53
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
        
networks:
  portainer_default:
    external: true

    services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 172.30.0.10
    restart: unless-stopped

volumes:
  portainer_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8180:80/tcp"
      - "8443:443/tcp"
      - "3000:3000/tcp"
    volumes:
      - /opt/adguardhome/work:/opt/adguardhome/work
      - /opt/adguardhome/conf:/opt/adguardhome/conf
     environment:
      - TZ=Africa/Nairobi
    networks:
      portainer_default:
        ipv4_address: 172.30.0.53
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
        
networks:
  portainer_default:
    external: true

    
