services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 172.30.0.10
    restart: unless-stopped

volumes:
  portainer_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
