services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8180:80/tcp"
      - "8443:443/tcp"
      - "3000:3000/tcp"
    volumes:
      - /opt/adguardhome/work:/opt/adguardhome/work
      - /opt/adguardhome/conf:/opt/adguardhome/conf
      - /opt/adguardhome/logs:/opt/adguardhome/logs
    environment:
      - TZ=Africa/Nairobi
      - ADGUARDHOME_LOG_LEVEL=debug
    networks:
      portainer_default:
        ipv4_address: 172.30.0.53
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - /opt/nginx-proxy-manager/data:/data
      - /opt/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - portainer_default

services:
  samsung-tvplus:
    image: matthuisman/samsung-tvplus-for-channels
    container_name: samsung-tvplus
    restart: unless-stopped
    environment:
      - REGIONS=all
      - TZ=Africa/Nairobi
    ports:
      - "8182:80"
    networks:
      - portainer_default

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - --cleanup=true
      - --interval=21600
      - --log-level=debug
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer_default

networks:
  portainer_default:
    external: true
