services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    command:
      - --cleanup=true
      - --include-restarting
      - --interval=86400
      - --trace
    environment:
      TZ: 'Africa/Nairobi'
      DOCKER_HOST: tcp://docker-socket-proxy:2375
    volumes:
      - /home/lenadlm/.docker/config.json:/config.json
    networks:
      - portainer_default

networks:
  portainer_default:
    external: true
