services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - --cleanup=true
      - --include-restarting
      - --interval=86400
      - --trace
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    environment:
      - DOCKER_CONFIG=/config.json
    networks:
      - portainer_default

networks:
  portainer_default:
    external: true
