
services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: unless-stopped
    volumes:
      - /opt/docker/crowdsec/config:/etc/crowdsec
      - /opt/docker/crowdsec/data:/var/lib/crowdsec/data
      - /var/log:/var/log:ro  # Read-only access to logs
    environment:
      - COLLECTIONS=crowdsecurity/base-http-scenarios crowdsecurity/linux
    networks:
      - external_network

  cloudflare-bouncer:
    image: crowdsecurity/cloudflare-bouncer
    container_name: cloudflare-bouncer
    restart: unless-stopped
    environment:
      - CF_API_TOKEN=your_cloudflare_api_token
      - CF_ZONE_ID=your_cloudflare_zone_id
      - CROWDSEC_LAPI_URL=http://crowdsec:8080/
    depends_on:
      - crowdsec
    networks:
      - external_network

networks:
  external_network:
    external: true
