services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Africa/Nairobi
    volumes:
      - /docker/homeassistant/config:/config
      - /var/run/dbus:/var/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
   # devices:
   #   - /dev/ttyUSB0:/dev/ttyUSB0  # adjust based on your device
   #   - /dev/ttyACM0:/dev/ttyACM0  # for Z-Wave/Zigbee USB sticks
