version: '3.8'

services:
  xteve:
    image: tinyserve/xteve:latest
    container_name: xteve
    restart: unless-stopped
    environment:
      - TZ=Africa/Nairobi
    ports:
      - "34400:34400"
    volumes:
      - /mnt/d/data/docker/xteve/config:/etc/xteve/config
      - /mnt/d/data/docker/xteve/backups:/etc/xteve/backups
      - /mnt/d/data/docker/xteve/logs:/etc/xteve/logs
    privileged: true
    networks:
      - portainer_default
    dns:
      - 172.30.0.53
    logging:
      options:
        max-size: "10m"
        max-file: "5"

networks:
  portainer_default:
    external: true
