services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5679:5678"
    environment:
      - N8N_HOST=IP
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=sth
      - N8N_BASIC_AUTH_PASSWORD=pwd
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - /docker/n8n/data:/home/node/.n8n
      - /docker/n8n/files:/files
    networks:
      - external_network
    restart: unless-stopped
    stop_grace_period: 60s

networks:
  external_network:
    external: true
