version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=1212
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1212
      - N8N_HOST=192.168.1.55
      - N8N_PORT=5678
      - WEBHOOK_URL=http://192.168.1.55:5678/
    volumes:
      - /docker/n8n/n8n_data:/home/node/.n8n
    depends_on:
      - db
    networks:
      - internal_network

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=1212
      - POSTGRES_DB=n8n
    volumes:
      - /docker/n8n/postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

networks:
  internal_network:
    external: true
