services: 
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - VERSION=docker
      # - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 32400:32400
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      internal_network:
        ipv4_address: 172.30.0.32
    volumes:
      - /docker/plex/config:/config
      - /mnt/d/data/media:/media

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    ports:
      - 8181:8181
    networks:
      - internal_network
    volumes:
      - /docker/plex/tautulli/config:/config

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - JELLYFIN_CACHE_DIR=/config/cache
      - LIBVA_DRIVER_NAME=iHD
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      - internal_network
    volumes:
      - /docker/jellyfin/library:/config
      - /mnt/d/data/media:/data

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Africa/Nairobi
      - PUID=1000
      - PGID=1000   
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - internal_network
    cap_add:
      - CHOWN
      - FOWNER
    volumes:
      - /docker/syncthing/config:/config:rw
      - /docker:/docker:rw
      - /mnt/d:/mnt/d:rw

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - TRANSMISSION_WEB_HOME= #optional
      - USER=leo
      - PASS=leo
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - internal_network
    volumes:
      - /docker/transmission/data:/config
      - /mnt/d/downloads:/downloads
      - /mnt/d/tmp:/watch
    
networks:
  internal_network:
    external: true
