services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - external_network
      
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - VERSION=docker
      # - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 32400:32400
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      internal_network:
        ipv4_address: 172.30.0.32
    volumes:
      - /docker/plex/config:/config
      - /mnt/d/data/media:/media

  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    restart: unless-stopped
    depends_on:
      - plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - KOMETA_CONFIG=/config/config.yml
      - KOMETA_TIME=21:00
    networks:
      - internal_network
    volumes:
      - /mnt/plex/kometa/config:/config

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    ports:
      - 8181:8181
    networks:
      - internal_network
    volumes:
      - /docker/plex/tautulli/config:/config

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - JELLYFIN_CACHE_DIR=/config/cache
      - LIBVA_DRIVER_NAME=iHD
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      internal_network:
        ipv4_address: 172.30.0.15
    volumes:
      - ${DATADIR}/jellyfin/library:/config
      - /d/data/media:/data


  xteve:
    image: tinyserve/xteve:latest
    container_name: xteve
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Africa/Nairobi
    networks:
      - internal_network
    dns:
      - 172.30.0.53
      - 172.20.0.53
    ports:
      - "34400:34400"
    volumes:
      - ${DATADIR}/xteve:/etc/xteve

networks:
  internal_network:
    external: true
