  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000 
      - PGID=1000
      - TZ=Africa/Nairobi
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      - external_network
    cap_add:
      - CHOWN
      - FOWNER
    volumes:
      - ${DATADIR}/syncthing/config:/config
      - ${DATADIR}:/opt/d/data/docker
      - /d/data:/opt/d/data
      - /f/data:/opt/f/data
