services:
  xteve:
    image: tinyserve/xteve:latest
    container_name: xteve
    restart: unless-stopped
    environment:
      - TZ=Africa/Nairobi
    ports:
      - "34400:34400"
    volumes:
      - /opt/xteve/:/etc/xteve
      - /opt/xteve/config/:/etc/xteve/config
      - /opt/xteve/backups/:/etc/xteve/backups
    networks:
      - portainer_default
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          memory: "256M"
    user: "1001:1001"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:34400"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 2m

networks:
  portainer_default:
    external: true
