services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Africa/Nairobi
    networks:
      - internal_network
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/dockhand/data:/app/data
    restart: unless-stopped

networks:
  internal_network:
    external: true
