name: adguardhome
services:
  adguardhome:
    image: adguard/adguardhome:latest
	restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp
	    - 8443:443/tcp
      - 3000:3000/tcp
    volumes:
      - /opt/adguardhome/conf:/opt/adguardhome/conf
      - /opt/adguardhome/work:/opt/adguardhome/work  
	networks:
		default:
			driver: bridge
	driver: "json-file"
	options:
		max-file: "10"
		max-size: "10m"
