services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8180:80/tcp"
      - "8443:443/tcp"
      - "3000:3000/tcp"
    volumes:
      - /opt/adguardhome/work:/opt/adguardhome/work
      - /opt/adguardhome/conf:/opt/adguardhome/conf
    environment:
      - TZ=Africa/Nairobi
    networks:
      portainer_default:
        ipv4_address: 172.30.0.53
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 1m

volumes:
  adguard_data:

networks:
  portainer_default:
    external: true
