services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8180:80/tcp"
      - "8443:443/tcp"
      - "3000:3000/tcp"
    volumes:
      - /data/docker/adguardhome/conf:/data/adguardhome/conf
      - /data/docker/adguardhome/work:/data/adguardhome/work  
    networks:
      portainer_default:
        ipv4_address: 172.30.0.53
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"

networks:
  portainer_default:
    external: true
