services:
  netbird:
    image: netbirdio/netbird:latest
    container_name: netbird
    ports:
      - "51820:51820/udp" # WireGuard port
    environment:
      - NETBIRD_CONFIG=/etc/netbird/config
    volumes:
      - /opt/netbird/config:/etc/netbird
    networks:
      network:
        ipv4_address: 172.20.0.2 # Fixed IP for NetBird container
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1" # Necessary for WireGuard
    restart: unless-stopped

  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "8180:80/tcp"
      - "8443:443/tcp"
      - "3000:3000/tcp"
    volumes:
      - /opt/adguard/work:/opt/adguardhome/work
      - /opt/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=Africa/Nairobi
    networks:
      network:
        ipv4_address: 172.20.0.53 # Fixed IP for AdGuard container
    restart: unless-stopped

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
