services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/d/data/docker/jellyfin/config:/config
      - /mnt/d/data/docker/jellyfin/cache:/cache
      - /mnt/d/data/docker/media:/media
    ports:
      - "8096:8096"  # Jellyfin default port
    networks:
      - portainer_default  # Use the existing portainer_default network
    dns:
      - 172.30.0.53
    logging:
      options:
        max-size: "10m"
        max-file: "5"

networks:
  portainer_default:
    external: true  # Tells Docker Compose to use the existing external network
