services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    environment:
      DOCKER_HOST: tcp://docker-socket-proxy:2375
    ports:
      - 8880:8080
    networks:
      - portainer_default

networks:
  portainer_default:
    external: true
