services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: ts-gcp
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_UP_ARGS=--advertise-tags=tag:dev --advertise-routes=10.128.0.0/24
    volumes:
      - /docker/tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - external_network
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  nginx:
    image: nginx
    depends_on:
      - tailscale
    network_mode: service:tailscale
    
networks:
  external_network:
    external: true
