services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: ts-gcp
    environment:
      - TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /docker/tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - external_network
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  nginx:
    image: nginx
    depends_on:
      - tailscale
    networks:
      - external_network
networks:
  external_network:
    external: true
