services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    networks:
      portainer_default:
        ipv4_address: 172.30.0.53
    environment:
      TZ: "Africa/Nairobi"
      WEBPASSWORD: "pihole"
    volumes:
      - /mnt/d/data/docker/pihole/etc-pihole:/etc/pihole
      - /mnt/d/data/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

networks:
  portainer_default:
    external: true
