services:
  stirling:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    ports:
      - "9080:8080"
    environment:
      - TZ=Africa/Nairobi
      - SECURITY_ENABLE_LOGIN=true
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_INITIALLOGIN_USERNAME=<username>
      - SECURITY_INITIALLOGIN_PASSWORD=<password>
    volumes:
      - /opt/stirling/media:/media:ro
      - /opt/stirling/config:/config
      - /opt/stirling/data:/usr/share/tessdata
    restart: unless-stopped
    networks:
      - portainer_default

networks:
  portainer_default:
    external: true
