services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - internal_network
    restart: unless-stopped

  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    ports:
      - 100.70.60.70:3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/dockhand/data:/app/data
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 100.70.60.70:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

#  hbbs:
#    container_name: hbbs
#    image: rustdesk/rustdesk-server:latest
#    #environment:
#      #- ALWAYS_USE_RELAY=Y
#    command: hbbs
#    volumes:
#      - /docker/rust/data:/root
#    network_mode: "host"
#    depends_on:
#      - hbbr
#    restart: unless-stopped

#  hbbr:
#    container_name: hbbr
#    image: rustdesk/rustdesk-server:latest
#    command: hbbr
#    volumes:
#      - /docker/rust/data:/root
#    network_mode: "host"
#    restart: unless-stopped

#  tailscale:
#    image: tailscale/tailscale:latest
#    container_name: tailscale-exit
#    hostname: ubuntu-exit-node
#    network_mode: host
#    command: tailscaled
#    cap_add:
#      - NET_ADMIN
#      - SYS_MODULE
#    devices:
#      - /dev/net/tun:/dev/net/tun
#    volumes:
#      - /docker/tailscale:/var/lib/tailscale
#    environment:
#      - TS_STATE_DIR=/var/lib/tailscale
#      - TS_USERSPACE=false
#    restart: unless-stopped


networks:
  internal_network:
    external: true
