services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 32400:32400
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      portainer_default:
        ipv4_address: 172.30.0.32
    dns:
      - 172.30.0.53
    volumes:
      - ${DATADIR}/plex/config:/config
      - /d/data/media:/media

  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - KOMETA_CONFIG=/config/config.yml
      - KOMETA_TIME=20:00
    networks:
      - portainer_default
    dns:
      - 172.30.0.53
    volumes:
      - ${DATADIR}/plex/kometa/config:/config

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - JELLYFIN_CACHE_DIR=/config/cache
      - LIBVA_DRIVER_NAME=iHD
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      portainer_default:
        ipv4_address: 172.30.0.15
    volumes:
      - ${DATADIR}/jellyfin/library:/config
      - /d/data/media:/data

  samsung-tvplus:
    image: matthuisman/samsung-tvplus-for-channels
    container_name: samsung-tvplus
    restart: unless-stopped
    environment:
      - TZ=Africa/Nairobi
    ports:
      - "8182:80"
    networks:
      - portainer_default
    dns:
      - 172.30.0.53

  xteve:
    image: tinyserve/xteve:latest
    container_name: xteve
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Africa/Nairobi
    networks:
      - portainer_default
    dns:
      - 172.30.0.53
    ports:
      - 34400:34400
    volumes:
      - ${DATADIR}/xteve:/etc/xteve
    logging:
      options:
        max-size: "10m"
        max-file: "5"

networks:
  portainer_default:
    external: true
