services:
  jellyfin:
    image: jellyfin/jellyfin:latest  # Jellyfin Docker image
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - JELLYFIN_CACHE_DIR=/cache
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_DATA_DIR=/config
      - JELLYFIN_CONFIG_DIR=/config/config
    volumes:
      - /mnt/d/data/docker/jellyfin/cache:/cache
      - /mnt/d/data/docker/jellyfin/log:/config/log
      - /mnt/d/data/docker/jellyfin/data:/config
      - /mnt/d/data/docker/jellyfin/config:/config/config
      - /mnt/d/data/docker/media:/media
      - /usr/bin/ffmpeg:/usr/bin/ffmpeg:ro
    ports:
      - "8096:8096"  # Jellyfin default port
    networks:
      - portainer_default
    dns:
      - 172.30.0.53
    privileged: true
    logging:
      options:
        max-size: "10m"
        max-file: "5"

networks:
  portainer_default:
    external: true
