services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /opt/dashy/config:/app/config
      - /opt/dashy/data:/app/public
    environment:
      - NODE_ENV=production
      - BASE_URL=/
    networks:
      - portainer_default

    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 45s

networks:
  portainer_default:
    external: true
