version: "3.8"

services:
  samsung-tvplus:
    image: matthuisman/samsung-tvplus-for-channels
    container_name: samsung-tvplus
    restart: unless-stopped
    environment:
      - REGIONS=all
      - TZ=Africa/Nairobi
    ports:
      - "8182:80"
    networks:
      - portainer_default
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

networks:
  portainer_default:
    external: true
