services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - external_network

  #cloudflare-ddns:
  #  image: favonia/cloudflare-ddns:latest
  #  restart: unless-stopped
  #  user: "1000:1000"
  #  read_only: true
  #  cap_drop: [all]
  #  security_opt: [no-new-privileges:true]
  #  environment:
  #    - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
  #    - DOMAINS=${DOMAINS}
  #    - PROXIED=true
  #  networks:
  #    - external_network

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    networks:
      - external_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - ${DATADIR}/duckdns/config:/config
