services: 
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    network_mode: host
    environment:
      - TZ=Africa/Nairobi
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    volumes:
      - /docker/adguardhome/work:/opt/adguardhome/work
      - /docker/adguardhome/conf:/opt/adguardhome/conf
    tmpfs:
      - /tmp
      - /run
